# Generated by Django 6.0.3 on 2026-03-24 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issue_type', models.CharField(choices=[('Water', 'Water'), ('Electricity', 'Electricity'), ('Roads', 'Roads'), ('Waste', 'Waste')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
