# Generated by Django 6.0.3 on 2026-03-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_issue_options_issue_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Optional contact number for follow-up', max_length=20, null=True),
        ),
    ]
